name: challanges
version: '1.1'
main: de.mathisburger.Main
api-version: '1.20'
load: STARTUP

commands:
  randomizer:
    description: Starts the randomizer challange
    usage: /randomizer
  randomizerDebug:
    description: Used for debug of randomizer challange
    usage: /randomizerDebug
  backpack:
    description: Opens the team backpack
    usage: /backpack
