name: challanges
version: '1.1'
main: de.mathisburger.Main
api-version: '1.20'
load: STARTUP

commands:
  config:
    description: Opens config inv
    usage: /config
  randomizerDebug:
    description: Used for debug of randomizer challange
    usage: /randomizerDebug
    permission: minecraft.command.op
  backpack:
    description: Opens the team backpack
    usage: /backpack
  invLookup:
    description: Can be used to lookup a player inventory
    usage: /invlookup
    permission: minecraft.command.op

